using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Forms;
using VectorLandMesh.Land;
namespace Brave_New_World
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

            //
            int meshOnLevel = 0;
            
            //odds map will be generated by Map settings.
            int[] oddsMap = { 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4 };

            /*  CONSTS: Need To replace with class for map Properties
             * MAX_SECTIONS     : Max number of section each contour is divide in to.
             * MAX_LENGTH       : Max length of each Contours Vector
             * LEVELS           : Number of Levels for each mesh.
             * min number of Land Meshes per level
             */
            const int MAX_SECTIONS = 16, MAX_LENGTH = 10, LEVELS = 12;
            //test for map data. will be set in to class List
            List<LandMesh> mapMeshData = new List<LandMesh>();

            //used later in loop on [Line 46]
            LandMesh land;
            Map.InitializeSeed();
            //grabs a randum number form an odds map.
            meshOnLevel = oddsMap[Map.MapSeed.Next(0, oddsMap.Length - 1)];
            oddsMap[0] = 0;
            oddsMap[1] = 0;

            for (int x = LEVELS; x > 0;x--)
            {
                //adds new Contour for each existing mesh.                
                foreach (LandMesh mesh in mapMeshData)
                {
                    mesh.addNewContour();
                }

                //add new land mesh(s)
                for (int y = meshOnLevel; y > 0; y--)
                {
                    land = new LandMesh(new System.Windows.Point(0, 4), 10D, x);
                    mapMeshData.Add(land);
                }

                //grabs a randum number form an odds map.
                meshOnLevel = oddsMap[Map.MapSeed.Next(0, oddsMap.Length - 1)];
            }
            //adds new a Contour for existing meshes.
            foreach (LandMesh mesh in mapMeshData)
            {
                //add new contour to the end of every mesh
                mesh.addNewContour();
            }
            double drpo = mapMeshData[0].HeightLevel;
            //soon to be removed for Class Structure
            List<List<List<Vector>>> mapdata = new List<List<List<Vector>>>();

            mapdata.Add(new List<List<Vector>>());
            mapdata[0].Add(new List<Vector>());
            double theata = Map.MapSeed.Next(1, MAX_SECTIONS);
            int r = Map.MapSeed.Next(1, MAX_LENGTH);
            mapdata[0][0].Add(new Vector(Math.Cos(Math.PI * theata / (MAX_SECTIONS / 2)) * r, Math.Sin(Math.PI * theata / (MAX_SECTIONS / 2))) * r);
            Vector d = mapdata[0][0][0];
            MessageBox.Show(String.Format("[{3},{4}] | [{0},{1}], length of {2}", d.X, d.Y, d.Length, theata * 360 / MAX_SECTIONS,r));
        }
    }
}
